### PR TITLE
rewritten in Rust because C++ is filthy but also because I appreciate that you made it

### PR DESCRIPTION
**Pull request by ghost**
Hey!

Found somebody on Standable Discord server talk about [this article](https://docs.google.com/document/d/1BdyWxQhFoRkJVfsLvcPNHgvL-esUEE76WbDfguOVbMg/mobilebasic#h.vdziwi8m0bo1), so I went and checked it out and did what was told. Noticed you wrote a piece of software, and then I saw it was written in C++.

I took that as an banterous insult, so I rewrote it in Rust because that's all I know after migrating from Java 9 months ago.

I also made sure to add a runtime check for if you aren't running it as an Administrator or if VRChat is running. Also added a `Low` priority option because I had the power to.

Anyway, I hope this will help others further!

### CODE REVIEW

**Comment by ghost** [comment]
By the way, if you know of a way to make this program prompt UAC administrative privileges, that would be splendid. I couldn't figure it out so I just added a check. If you don't run it as Administrator, it'll bitch about `Access is denied. (os error 5)`.

**Comment by ghost** [comment]
Oh! If you're going to merge, make sure you edit the licence headers, `Cargo.toml` and `README.md` links to use your alias over mine.

**Comment by ghost** [comment]
> By the way, if you know of a way to make this program prompt UAC administrative privileges, that would be splendid. I couldn't figure it out so I just added a check. If you don't run it as Administrator, it'll bitch about `Access is denied. (os error 5)`.

Oh yeah, I managed to do it here: https://github.com/Kawaxte/vrc-priority-rs/commit/db5519956dafdb16599ccf6f83a404b6c1dec524

**Comment by BlueberryWolf** [comment]
I would merge this, but it's overcomplicating a silly problem which only occurs on Windows. The problem could be solved with a batch/powershell file or .reg files for different priorities, but I think rewriting a low level program in another low-level language for a program that sets 1 registry key is unnecessary. I do appreciate the effort though.

My C++ was written to be simple to understand, and robust. The problem is, most people who are setting vrchat's priority are either not tech savvy, or elitists; it's a dunning-kruger kind of optimization.

The problem with writing such a program in something like batch is, a lot of those who aren't tech savvy will have antiviruses that delete any .bat file regardless of it's content. Similar issue with powershell, where the system is configured to not allow "untrusted scripts" by default.
I wrote it in C++ because it's 1 file which is simple to understand, can be built, but most people will just run the binary and forget, because most people will not be bothered to compile from source.
image

I'm not sure that rewriting the program in rust actually solves any problems, considering that the original program is a robust, set and forget kind of program. I'm not sure that being memory safe is necessarily important.

Maybe I could make a separate rust branch, but this is just a program you run once, delete, and forget. Since it's just setting a registry key, and the optimization itself generally makes a marginal difference.

**Comment by ghost** [comment]
That's a fair view. On my end of things, I got sort of bored and wanted to scratch that itch of writing code, and there's nothing better than rewriting something in a copycat way, but in *my* way, in a language that doesn't aim for my jugular, and is also easier to read.

It was fun trying to make some changes that applied some failsafes, like the part where a VRChat process is running and you're trying to run this program WHILE VRChat is awake.

Also, I already gave people a pre-compiled binary in the `Releases` tab, but those who want to compile it on their own can compile it on their own, as given in the instructions, *if* they don't trust my pre-made executable.

**Comment by parabirb** [comment]
> in a language that doesn't aim for my jugular, and is also easier to read.

rust is NOT easier to read than c++ lmao

**Comment by ghost** [comment]
> > in a language that doesn't aim for my jugular, and is also easier to read.
> 
> rust is NOT easier to read than c++ lmao

I beg to differ. If it was easier to read and work with, would've been the language I had used after Java. Fortunately, that was not the case. Alien once, alien forever.

**Pull request closed without merging**
